# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: BiA-PoL blog
author: Marcelo Zoccoler, Johannes MÃ¼ller, Till Korten, Ryan Savill, Mara Lampert, Robert Haase, DFG Cluster of Excellence "Physics of Life", TU Dresden
copyright: "2023"
logo: images/biapol_logo.png
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: BiA-PoL_blog.tex

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/lazigu/blog
  path_to_book: docs
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions:
    - html_image
